# docker-compose.yml
version: '3.8'

services:
  parking-alot:
    container_name: parking-alot
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - .:/parking
