# docker-compose.yml
version: '3.8'

services:
  parking-alot:
    container_name: parking-alot
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - .:/src
    depends_on:
      - mysql-parking

  mysql-parking:
    container_name: mysql-parking
    image: mysql
    restart: always
    ports:
        - "3306:3306"
    environment:
      - MYSQL_DATABASE=parking_alot
      - MYSQL_USER=parking
      - MYSQL_PASSWORD=parking
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./mysql-parking:/var/lib/mysql
